package centrocultural.ui;

import centrocultural.controller.GestionAlumnos;
import centrocultural.controller.GestionCursos;
import centrocultural.controller.GestionInscripcion;
import centrocultural.controller.GestionTematicas;
import centrocultural.excepciones.ExistException;
import centrocultural.model.Curso;
import centrocultural.model.Participante;
import centrocultural.model.Tematica;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giselaRotatori
 */
public class JFInscripcion extends javax.swing.JFrame {
    private final GestionTematicas ctrlTematica = new GestionTematicas();
    private final GestionCursos ctrlCurso = new GestionCursos();
    private final GestionAlumnos ctrlAlumnos = new GestionAlumnos();
    private final GestionInscripcion ctrlInscripcion = new GestionInscripcion();
    
    private Participante participante = null;
    private List<Integer> cursoIds = new ArrayList<>();
    
    ButtonGroup rdGroup = new ButtonGroup();
    /**
     * Creates new form JFPrincipale
     */
    public JFInscripcion() {
        initComponents();
        cargaCBTematica();
        this.setResizable(false);
        rdGroup.add(rbNoRegistrado);
        rdGroup.add(rbRegistrado);
        this.setSize(800,600);
        lbMensaje.setText("");
    }
    
    private void cargarTabla(){
        this.jtCursos.removeAll();
        List<Curso> lista = ctrlCurso.getCursosByTematica(cbTematica.getSelectedItem().toString()); //ctrlCurso.getAllCursos();
        Object[][] data = new Object[lista.size()][6];
        String[] columnNames = {"Nombre", "Profesor", "Aula", "Duracion", "Carga Horaria", "Cupos"};
        cursoIds.clear();
        for(int i = 0; i<lista.size(); i++){
            Curso aux = lista.get(i);
            cursoIds.add(aux.getId());
            data[i][0] = aux.getNombre();
            data[i][1] = aux.getProfesor().getNombre()+ " " + aux.getProfesor().getApellido();
            data[i][2] = aux.getAula();
            data[i][3] = aux.getDuracion() + " meses";
            data[i][4] = aux.getCargaHoraria() + " hs/semana";
            data[i][5] = aux.getCuposDisponibles();
        }
        DefaultTableModel modelo = new DefaultTableModel(data, columnNames){
                @Override
                public boolean isCellEditable(int row, int column) {
                   return false;
                }
        };
        this.jtCursos.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEstudiante = new javax.swing.JPanel();
        rbRegistrado = new javax.swing.JRadioButton();
        rbNoRegistrado = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        lbMensaje = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbTematica = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCursos = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnInscribirse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Inscripción");

        jpEstudiante.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 0, 12))); // NOI18N

        rbRegistrado.setSelected(true);
        rbRegistrado.setText("Estudiante Registrado");

        rbNoRegistrado.setText("Estudiante No Registrado");

        jLabel1.setText("Ingrese su e-mail");

        txtMail.setToolTipText("Ingrese Correo Electronico");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Apellido:");

        lbMensaje.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lbMensaje.setText("Muestra mensaje");

        javax.swing.GroupLayout jpEstudianteLayout = new javax.swing.GroupLayout(jpEstudiante);
        jpEstudiante.setLayout(jpEstudianteLayout);
        jpEstudianteLayout.setHorizontalGroup(
            jpEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbRegistrado)
                    .addComponent(rbNoRegistrado))
                .addGroup(jpEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEstudianteLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEstudianteLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jpEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEstudianteLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbApellido))
                            .addGroup(jpEstudianteLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNombre)))))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(jpEstudianteLayout.createSequentialGroup()
                .addComponent(lbMensaje)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpEstudianteLayout.setVerticalGroup(
            jpEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEstudianteLayout.createSequentialGroup()
                .addGroup(jpEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEstudianteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(jpEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbNombre)))
                    .addGroup(jpEstudianteLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(rbRegistrado)
                        .addGap(18, 18, 18)
                        .addComponent(rbNoRegistrado)))
                .addGap(18, 18, 18)
                .addGroup(jpEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(lbMensaje))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cursos Vigentes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 0, 12))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 600));

        jLabel4.setText("Temáticas:");

        cbTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTematicaActionPerformed(evt);
            }
        });

        jtCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Profesor", "Aula", "Duración", "Carga Horaria", "Cupo"
            }
        ));
        jScrollPane1.setViewportView(jtCursos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cbTematica, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");

        btnInscribirse.setText("Inscribirse");
        btnInscribirse.setEnabled(false);
        btnInscribirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInscribirse, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInscribirse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTematicaActionPerformed
        // TODO add your handling code here:
        cargarTabla();
    }//GEN-LAST:event_cbTematicaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        lbNombre.setText("");
        lbApellido.setText("");
        participante = null;
        if(!"".equals(txtMail.getText())){
            obtenerParticipante();
        }else{
            lbMensaje.setText("Debe completar el campo Email");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnInscribirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirseActionPerformed
        // TODO add your handling code here:
        int fila = jtCursos.getSelectedRow();
        if(fila != -1){
            Curso curso = ctrlCurso.getCursoById(cursoIds.get(fila));
            try{
                int condicion = ctrlInscripcion.nuevaInscripcion(curso, participante);
                cargarTabla();
                String mensaje;
                if(condicion == 1)
                    mensaje = "Inscripcion al curso completada";
                else
                    mensaje = "Su incripcion ha sido condicional, debe esperar a que se";
                JOptionPane.showMessageDialog(this, "Inscripcion al curso completada");
            }catch(ExistException ee){
                lbMensaje.setText(ee.getMessage());
            }
        }else{
            lbMensaje.setText("Debe seleccionar un curso");
        }
        
    }//GEN-LAST:event_btnInscribirseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFInscripcion().setVisible(true);
            }
        });
    }
    
    
    //Metodos
    private List<Tematica> traerTematicas(){
        return ctrlTematica.traerTematicas();
    }
    
    private void cargaCBTematica(){
        List<Tematica> lista = traerTematicas();
        for(Tematica t : lista){
            cbTematica.addItem(t.getNombre());
        }
    }
    
    public String getEmail(){
        return txtMail.getText();
    }
    
    private void activarRegistro(){
        JFRegistro registro = new JFRegistro(this);
        this.setVisible(false);
        registro.setVisible(true);
    }
    
    public void obtenerParticipante(){
        lbMensaje.setText("");
        participante = ctrlAlumnos.getParticipante(txtMail.getText());
        if(participante != null){
            lbNombre.setText(participante.getNombre());
            lbApellido.setText(participante.getApellido());
            btnInscribirse.setEnabled(true);
        }else{
            activarRegistro();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInscribirse;
    private javax.swing.JComboBox<String> cbTematica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpEstudiante;
    private javax.swing.JTable jtCursos;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbMensaje;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JRadioButton rbNoRegistrado;
    private javax.swing.JRadioButton rbRegistrado;
    private javax.swing.JTextField txtMail;
    // End of variables declaration//GEN-END:variables
}
